sudo: false

language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pycodestyle --ignore E501 ascii2graph
  - pytest -vv -s ascii2graph/*

notifications:
  email: false
